export const CHANGE_ACTIVITYINFO = 'CHANGE_ACTIVITYINFO'
export const CHANGE_ACTIVITYLIST = 'CHANGE_ACTIVITYLIST'
export const CHANGE_GAMEINFO = 'CHANGE_GAMEINFO'
export const CHANGE_SALEINFO = 'CHANGE_SALEINFO'